reads: "paried"
zip_fastq : "/media/pronozin/Disk_2/Assambly_pipeline/"
fastp :
  average_qual: 0
  length_required: 5 
  thread: 1 
  overlap_len_require: 2
trinity:
  mode: "each" # "each" of "file"
  max_memory: "10G"
  CPU: 2
  genome_guided_max_intron: 500000
SOAP:
  max_rd_len: 100
  rd_len_cutof: 100
  avg_ins: 127
  reverse_seq: 0
  asm_flags: 3
  map_len: 32
  n_cpu: 2
reference: "ref/GCF_000186305.1_Python_molurus_bivittatus-5.0.2_genomic.fna" 
samtools:
  thr: 2
